name: Pull locales from PARANOIDAL

env:
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-locales-files:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache paranoidal-git
        uses: actions/cache@v4
        with:
          path: .nuke/temp/paranoidal-git
          key: update-locales-files

      - name: Extract localization to JSONs
        run: ./build.sh ExtractLocalizationToJsons

      - name: Commit and push if changed
        run: |
          git config --global user.email 'skproch@yandex.ru'
          git config --global user.name 'SKProCHs Bot'
          git diff --quiet && git diff --staged --quiet || (git add . && git commit -am 'Updated localization from Factorio Paranoidal mods' && git push)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
